### ISSUE TITLE
Implementation details

### ISSUE THREAD

**Issue by wjun0830** [bo-miao/HTR#6]
Hello. 

May I ask for the implementation details for training Mevis?

Thanks

**Comment by bo-miao** [comment]
Hi, 

Using a pretrained VideoSwinT backbone, we trained the model directly on MeVIS for 3 epochs.

`BACKBONE="video_swin_t_p4w7"
BACKBONE_PRETRAINED="../pretrained_backbones/swin_tiny_patch244_window877_kinetics400_1k.pth"
OUTPUT_DIR="../results/HTR_${BACKBONE}_scratch_mevis"
EXP_NAME="HTR_${BACKBONE}_scratch_mevis"

CUDA_VISIBLE_DEVICES=${GPUS} OMP_NUM_THREADS=${CPUS_PER_TASK} torchrun --master_port ${PORT}  --nproc_per_node=${GPUS_PER_NODE} main.py \
  --with_box_refine --binary --freeze_text_encoder \
  --dataset_file 'mevis' \
  --exp_name=${EXP_NAME} \
  --output_dir=${OUTPUT_DIR} \
  --backbone=${BACKBONE} \
  --backbone_pretrained=${BACKBONE_PRETRAINED} \
  --use_checkpoint \
  --epochs 3 --lr_drop 1 2 \`

**Comment by wjun0830** [comment]
Thank you!
